version: "3.0"

services:
  mongodb:
    container_name: mongodb-${DB_CONTAINER_NAME}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - ${MONGO_DB_DEPLOY_PORT}:27017

  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_DB_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - ${POSTGRES_DB_DEPLOY_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio-local
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - "minio_data:/data"
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"

volumes:
  minio_data:
    driver: local
  db-data:
