version: "3.0"

services:
  mongodb:
    container_name: mongodb-${DB_CONTAINER_NAME}
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    ports:
      - ${MONGO_DB_DEPLOY_PORT}:27017
